name: Daily Fyers Auto Login

on:
  schedule:
    - cron: '25 3 * * 1-5'
  workflow_dispatch:

jobs:
  fyers-login:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # YE HAI ASLI FIX: ref: main
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests pyotp fyers-apiv3

      - name: Generate Fyers Token
        run: python generate_token.py

      - name: Save Token To Repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add fyers_token.txt
          git commit -m "Auto Updated Daily Token" || echo "No changes to commit"
          git push origin main
