name: Daily Fyers Auto Login

on:
  schedule:
    - cron: '25 3 * * 1-5'
  workflow_dispatch:

jobs:
  fyers-login:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests pyotp fyers-apiv3

      - name: Generate Token & Save via API
        env:
          # Python script ko direct save karne ke liye token pass kiya hai
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python generate_token.py
